name: app_pym
description: Application PYM

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <2.9.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^4.0.0 # bloclibrary.dev
  http: ^0.12.1 # dart.dev
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  connectivity: ^0.4.8+2 # flutter.dev # Not web compatible
  get_it: ^4.0.2 # fluttercommunity.dev
  json_annotation: ^3.0.1 # dart.dev
  firebase_core: ^0.4.4+3
  firebase_messaging: ^6.0.15 # Not web compatible
  rxdart: ^0.24.0
  injectable: ^0.3.0
  mockito: ^4.1.1 # dart.dev
  path_provider: ^1.6.8 # Not web compatible
  shared_preferences: ^0.5.7+2
  google_maps_flutter: ^0.5.27+3 # Not web compatible
  font_awesome_flutter: ^8.8.1
  webview_flutter: ^0.3.21 # Not web compatible
  flutter_unity_widget:  # Not web compatible
    git:
      url: git://github.com/Projet-Industriel-2020-PYM-APP/flutter-unity-view-widget.git
      ref: e311b2a2f5a84bccad10a140d2a9919784ec755e
  permission_handler: ^5.0.0+hotfix.5 # Not web compatible
  geolocator: ^5.3.1
  flutter_compass: ^0.4.2+1
  url_launcher: ^5.4.7
  freezed_annotation: ^0.7.1
  package_info: ^0.4.0+18
  flutter_markdown: ^0.3.5
  breakpoint: ^1.0.1+2
  archive: ^2.0.13
  intl: ^0.16.1
  cached_network_image: ^2.2.0+1

dependency_overrides:
  dartx: 0.4.1
  path: 1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  hive_generator: ^0.7.0+2
  build_runner: any
  json_serializable: ^3.3.0 # dart.dev
  injectable_generator: ^0.3.5
  extra_pedantic: 1.2.0
  freezed: ^0.10.8
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: false
  ios: true
  image_path: 'assets/icon/icon.png'
  adaptive_icon_background: '#ffffff'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/cartographie/
    - assets/images/graphique/
    - assets/images/actualite/
    - assets/images/mobilite/
    - assets/markdown/
    - assets/icon/
    - assets/bus_data/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
